### ISSUE TITLE
different results from iglue

### ISSUE THREAD

**Issue by lizhiustc** [marvl-challenge/marvl-code#2]
Hello, I notice that the average result of zero-shot. in   [marvl-code](https://arxiv.org/pdf/2109.13238.pdf) mUNITER 54.0, xUNITER.  56.1  is higher than your recent work [iglue](https://arxiv.org/pdf/2201.11732.pdf)  mUNITER  53.72  xUNITER   54.59 . Especially for xUNITER ( 54.59  is about 1.5 points lower that  56.1)
I  reproduced your experiment with [marvl-code Repository](https://github.com/marvl-challenge/marvl-code) and the results are close to iglue . Can you give me some advice to imporve the results ? Or I should regard the iglue as baseline ?

**Comment by e-bug** [comment]
Hi, I thought the lower scores in IGLUE were due to a longer max sequence length and random seed variance. 
But you got similar ones using this repository.
Maybe you can try lower casing the text? Let me know if this helps!
