### ISSUE TITLE
Is img_segment_ids used for evaluation?

### ISSUE THREAD

**Issue by lonestar234028** [marvl-challenge/marvl-code#3]
Hi @e-bug Is this useful information for the model? 
https://github.com/marvl-challenge/marvl-code/blob/master/volta/volta/datasets/marvl_dataset.py#L163
I saw you not using it

**Comment by e-bug** [comment]
Hi! 

We did not use it for training either [[here](https://github.com/marvl-challenge/marvl-code/blob/master/volta/volta/datasets/nlvr2_dataset.py)].

But indeed, I agree this info might be useful for the model.

**Comment by lonestar234028** [comment]
@e-bug  thanks!
